name: Update README

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes to the README
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master # Or another activity action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
        with:
          COMMIT_MSG: "Update profile README with recent activity"
          MAX_LINES: 10 # Limit the number of activity lines displayed
